import { useEffect, useMemo, useState } from 'react'

import {
  getOutputView,
  getOutputs,
  outputDownloadUrl,
  type OutputFile,
  type OutputWorkbook,
} from '../api/client'
import { Spinner } from './NewMapping'

export default function Mappings() {
  const [files, setFiles] = useState<OutputFile[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [selected, setSelected] = useState<string | null>(null)

  useEffect(() => {
    getOutputs()
      .then(setFiles)
      .catch((e) => setError(e.message))
      .finally(() => setLoading(false))
  }, [])

  if (selected) return <Viewer name={selected} onBack={() => setSelected(null)} />

  return (
    <div className="flex flex-col gap-4">
      <h2 className="text-2xl font-bold text-[#451DC7]">Completed mappings</h2>
      <p className="text-sm text-gray-600">Excel workbooks generated by the agent. Preview them here or download them.</p>

      {error && <p className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}

      {loading ? (
        <div className="flex items-center gap-3 text-indigo-700">
          <Spinner />
          Loading…
        </div>
      ) : files.length === 0 ? (
        <p className="rounded-xl border border-gray-200 bg-white p-4 text-sm text-gray-500">
          No mapping yet. Run an analysis from New mapping; the workbook will appear here.
        </p>
      ) : (
        <div className="flex flex-col gap-2">
          {files.map((f) => (
            <FileRow key={f.name} file={f} onView={() => setSelected(f.name)} />
          ))}
        </div>
      )}
    </div>
  )
}

function FileRow({ file, onView }: { file: OutputFile; onView: () => void }) {
  const when = new Date(file.modified).toLocaleString('en-GB', {
    dateStyle: 'medium',
    timeStyle: 'short',
  })

  return (
    <div className="flex items-center justify-between rounded-xl border border-gray-200 bg-white p-4 shadow-sm">
      <div>
        <div className="font-semibold text-gray-900">{file.name}</div>
        <div className="mt-1 text-xs text-gray-500">
          {when} · {file.size_kb} KB · {file.sheets.length} sheet{file.sheets.length > 1 ? 's' : ''}
        </div>
      </div>

      <div className="flex gap-2">
        <button
          onClick={onView}
          className="rounded-lg border border-indigo-500 px-3 py-2 text-sm font-medium text-indigo-600 hover:bg-indigo-50"
        >
          Preview
        </button>
        <a
          href={outputDownloadUrl(file.name)}
          className="rounded-lg bg-indigo-600 px-3 py-2 text-sm font-medium text-white hover:bg-indigo-700"
        >
          ⬇ Excel
        </a>
      </div>
    </div>
  )
}

function _norm(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]/g, '')
}

function coverageClass(header: string, value: string): string {
  if (_norm(header) !== 'coveragelevel') return ''

  const n = parseInt(value, 10)
  if (Number.isNaN(n)) return ''
  if (n >= 100) return 'bg-green-100 text-green-800 font-medium'
  if (n >= 40) return 'bg-amber-100 text-amber-800 font-medium'
  if (n > 0) return 'bg-red-50 text-red-700'
  return 'bg-red-100 text-red-700 font-medium'
}

function Viewer({ name, onBack }: { name: string; onBack: () => void }) {
  const [wb, setWb] = useState<OutputWorkbook | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [active, setActive] = useState(0)

  useEffect(() => {
    setLoading(true)
    getOutputView(name)
      .then((data) => {
        setWb(data)
        // Land on the first real mapping sheet, when available.
        const idx = data.sheets.findIndex((s) => s.headers.some((h) => _norm(h) === 'sourcecontrolid'))
        setActive(idx >= 0 ? idx : 0)
      })
      .catch((e) => setError(e.message))
      .finally(() => setLoading(false))
  }, [name])

  const sheet = useMemo(() => wb?.sheets[active] ?? null, [wb, active])

  return (
    <div className="flex flex-col gap-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <button onClick={onBack} className="rounded-lg border border-gray-300 px-3 py-2 text-sm hover:bg-gray-50">
            ← Back
          </button>
          <h2 className="text-xl font-bold text-[#451DC7]">{name}</h2>
        </div>

        <a href={outputDownloadUrl(name)} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-700">
          ⬇ Download Excel
        </a>
      </div>

      {error && <p className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}

      {loading ? (
        <div className="flex items-center gap-3 text-indigo-700">
          <Spinner />
          Reading workbook…
        </div>
      ) : wb && sheet ? (
        <>
          <div className="flex flex-wrap gap-1 border-b border-gray-200">
            {wb.sheets.map((s, i) => (
              <button
                key={s.name}
                onClick={() => setActive(i)}
                className={`rounded-t-lg px-3 py-1.5 text-sm transition ${
                  i === active ? 'bg-indigo-600 font-medium text-white' : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
                }`}
              >
                {s.name}
              </button>
            ))}
          </div>

          <div className="rounded-xl border border-gray-200 bg-white p-4 shadow-sm">
            {sheet.title && <h3 className="font-semibold text-gray-900">{sheet.title}</h3>}
            <p className="mt-1 text-xs text-gray-500">
              {sheet.total_rows} row{sheet.total_rows > 1 ? 's' : ''}
              {sheet.truncated && ' · preview limited to the first 2,000 rows — download the file to see everything'}
            </p>
          </div>

          <SheetTable sheet={sheet} />
        </>
      ) : null}
    </div>
  )
}

function SheetTable({ sheet }: { sheet: OutputWorkbook['sheets'][number] }) {
  if (sheet.headers.length === 0 && sheet.rows.length === 0) {
    return <p className="rounded-xl border border-gray-200 bg-white p-4 text-sm text-gray-500">Empty sheet.</p>
  }

  return (
    <div className="overflow-auto rounded-xl border border-gray-200 bg-white shadow-sm">
      <table className="min-w-full border-collapse text-left text-sm">
        <thead className="sticky top-0 bg-gray-50 text-xs uppercase tracking-wide text-gray-500">
          <tr>
            {sheet.headers.map((h, i) => (
              <th key={`${h}-${i}`} className="border-b border-gray-200 px-3 py-2 font-semibold">
                {h}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {sheet.rows.map((row, ri) => (
            <tr key={ri} className="border-b border-gray-100 last:border-0">
              {row.map((cell, ci) => (
                <td
                  key={`${ri}-${ci}`}
                  className={`max-w-[360px] whitespace-pre-wrap px-3 py-2 align-top ${coverageClass(sheet.headers[ci] ?? '', cell)}`}
                >
                  {cell}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}
